checkForUpdatesAutomatically: true
showFloatingNotifications: true
showMenuBarTitle: true
showMenuBarIcon: true
menuBarTitleTemplate: $PROFILE/$WORKSPACE_NUMBER
menuBarDisplayAliases: 'Built-in Retina Display=Main;LC32G5xT=Secondary;Benq GW2470=Tertiary  '
enableFocusManagement: true
centerCursorOnFocusChange: true
focusLeft: opt+h
focusRight: opt+l
focusUp: opt+j
focusDown: opt+k
focusFrontmostWindow: false
enableSwipeGestures: false
swipeThreshold: 2e-1
restartAppOnWakeUp: false
swipeLeft3FingerAction: previousWorkspace
swipeRight3FingerAction: nextWorkspace
swipeUp3FingerAction: none
swipeDown3FingerAction: none
swipeLeft4FingerAction: none
swipeRight4FingerAction: none
swipeUp4FingerAction: none
swipeDown4FingerAction: none
displayMode: static
centerCursorOnWorkspaceChange: true
changeWorkspaceOnAppAssign: true
activeWorkspaceOnFocusChange: true
autoAssignAppsToWorkspaces: false
skipEmptyWorkspacesOnSwitch: false
keepUnassignedAppsOnSwitch: false
restoreHiddenAppsOnSwitch: true
enableWorkspaceTransitions: false
showRecentWorkspaceWhenActivatedTwice: false
workspaceTransitionDuration: 3e-1
workspaceTransitionDimming: 2e-1
loopWorkspaces: true
loopWorkspacesOnAllDisplays: false
switchWorkspaceOnCursorScreen: false
alternativeDisplays: 'LC32G5xT=Built-in Retina Display;Benq GW2470=Built-in Retina
  Display  '
enablePictureInPictureSupport: true
switchWorkspaceWhenPipCloses: true
pipApps: []
pipScreenCornerOffset: 15
cornerHiddenApps: []
floatingApps:
- name: ChatGPT
  bundleIdentifier: com.openai.chat
  iconPath: /Applications/ChatGPT.app/Contents/Resources/AppIcon.icns
toggleTheFocusedAppFloating: ctrl+opt+f
enableSpaceControl: false
enableSpaceControlAnimations: true
enableSpaceControlTilesAnimations: true
spaceControlCurrentDisplayWorkspaces: false
spaceControlHideEmptyWorkspaces: false
spaceControlUpdateScreenshotsOnOpen: false
spaceControlNumberOfColumns: 0
enableIntegrations: false
runScriptOnLaunch: ''
runScriptOnWorkspaceChange: sketchybar --trigger flashspace_workspace_change WORKSPACE="$WORKSPACE"
  DISPLAY="$DISPLAY"
runScriptAfterWorkspaceChange: ''
runScriptOnProfileChange: sketchybar --reload
